Knock-Og/BE

src/main/java/com/project/comgle/config/WebSecurityConfig.java
src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
src/main/java/com/project/comgle/dto/request/LoginRequestDto.java
src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
src/main/java/com/project/comgle/dto/response/MessageResponseDto.java
src/main/java/com/project/comgle/entity/Company.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/exception/ErrorResponse.java
src/main/java/com/project/comgle/jwt/JwtAuthFilter.java
src/main/java/com/project/comgle/jwt/JwtUtil.java
src/main/java/com/project/comgle/repository/CompanyRepository.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/security/UserDetailsImpl.java
src/main/java/com/project/comgle/security/UserDetailsServiceImpl.java
src/main/java/com/project/comgle/service/MemberService.java

feat/10/signup-> dev
- 임시 company 작성
- 회원가입 기능

Feat : 회원가입 기능 #10

---

src/main/java/com/project/comgle/controller/AdminController.java
src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
src/main/java/com/project/comgle/dto/response/PermissionResponseDto.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/service/AdminService.java

feat/15/permision -> develop
- Admin Controller / Service 생성 
- MemberRepository에 permision 조건으로 전체조회하는 메서드 추가
- 응답을 위한 PermisionResponseDto 추가

Feat : 승인요청 계정 전체 리스트 조회 기능 (#15)

---

src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/service/MemberService.java

feat/13/checkEmail-> dev
- 이메일 중복 확인 기능
- 로그인 허가받은 사용자(permission) 확인 추가

Feat : 이메일 중복 확인 기능 (#13)

---

src/main/java/com/project/comgle/controller/AdminController.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/service/AdminService.java

feat/18/permision-member -> develop
- 회원 번호를 통해서 미승인 된 회원을 승인해주는 기능 구현

Feat : 미승인 회원 승인 기능 (#18)

---

src/main/java/com/project/comgle/controller/AdminController.java
src/main/java/com/project/comgle/dto/request/PositionRequestDto.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/service/AdminService.java

feat/19/chang-position -> develop
- ADMIN 페이지에서 해당 멤버의 직책을 변경 시 예외체크를 통한 직책 변경 기능

Feat : 직책 변경 기능 (#19)

---

src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/dto/request/CategoryRequestDto.java
src/main/java/com/project/comgle/repository/CategoryRepository.java
src/main/java/com/project/comgle/service/CategoryService.java

feat/27/add-category -> develop
- 카테고리 등록하는 기능 구현
- 카테고리 등록 시 중복체크

Feat : 카테고리 추가 기능 (#27)

---

src/main/java/com/project/comgle/controller/AdminController.java
src/main/java/com/project/comgle/service/AdminService.java

fix/35/del-permision -> develop
- 미 승인 회원 전체 조회하는 기능 제거
- 회원 승인 기능 제거
Closes #35

Fix : 회원 승인 및 미 승인 회원 전체 조회 기능 삭제 #35

---

src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/dto/request/CategoryRequestDto.java
src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/service/MemberService.java

feat/34/name-check -> develop
- 중복 회원 체크 기능 구현
- 불필요한 import 제거
- 이메일 & 이름 중복 체크로 인한 URL 변경

Feat : 중복 회원명 체크 #34

---

src/main/java/com/project/comgle/config/Init.java
src/main/java/com/project/comgle/controller/Init.java
src/main/java/com/project/comgle/dto/request/CompanyRequestDto.java
src/main/java/com/project/comgle/dto/request/Init.java
src/main/java/com/project/comgle/dto/response/Init.java
src/main/java/com/project/comgle/exception/Init.java
src/main/java/com/project/comgle/healthCheck/Init.java
src/main/java/com/project/comgle/jwt/Init.java
src/main/java/com/project/comgle/repository/Init.java
src/main/java/com/project/comgle/security/Init.java
src/main/java/com/project/comgle/service/Init.java

- config
- controller
- dto_request
- dto_response
- exception
- healthCheck
- jwt
- repository
- security
- service
file/39/Init_remove -> dev
- 위의 패키지마다 있는 Init 클래스 삭제
- 해당 사항 없음

File : 프로젝트 패키지마다 있는 Init 클래스 삭제 #39

---

src/main/java/com/project/comgle/config/WebSecurityConfig.java
src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/dto/request/SignupRequestDto.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/service/AdminService.java
src/main/java/com/project/comgle/service/MemberService.java

fix/33/regist-> develop
- 회원가입 시 사용했던 permision Entity, 회원가입 로직에서 제거
- 관리자 권한으로 회원을 등록하기 위한 권한 체크
- 이메일 중복확인
- 사용자명 중복 확인
- ADMIN 계정 회사명을 통하여 회사마다 분리하여 회원 등록 가능

Fix : 회원가입 기능 수정 (#33)

---

src/main/java/com/project/comgle/config/WebSecurityConfig.java
src/main/java/com/project/comgle/controller/AdminController.java
src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/dto/response/MemberResponseDto.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/service/AdminService.java
src/main/java/com/project/comgle/service/MemberService.java

feat/48/find-members -> develop
- Admin / Member 컨트롤러 처리 역할 분배
- 해당 사내 모든 회원 조회 기능 구현

Feat : 회원 전체 조회 기능 구현 (#48)

---

src/main/java/com/project/comgle/controller/PostController.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/entity/Post.java
src/main/java/com/project/comgle/entity/PostCategory.java
src/main/java/com/project/comgle/entity/enumSet/PositionEnum.java
src/main/java/com/project/comgle/repository/PostCategoryRepository.java
src/main/java/com/project/comgle/repository/PostRepository.java
src/main/java/com/project/comgle/service/MemberService.java
src/main/java/com/project/comgle/service/PostService.java

feat/24/update post-> dev
- 기존 중복이나 삭제 되는 경우 이상 없도록 변경했습니다.

Feat : 게시글 수정 기능 

---

src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/service/MemberService.java

feat/55/merge-issue -> develop
- 회원가입 기능 관리 도메인 변경 시 기존 메서드 삭제하지 않아서 발생한 문제

Fix : merge issue #55

---

src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/entity/Category.java
src/main/java/com/project/comgle/entity/Member.java
src/main/java/com/project/comgle/repository/CategoryRepository.java
src/main/java/com/project/comgle/repository/MemberRepository.java
src/main/java/com/project/comgle/service/CategoryService.java
src/main/java/com/project/comgle/service/PostService.java

feat/57/update-category -> develop
- 카테고리 생성 기능에서 생성 시 해당 Company 추가
- 수정 시 ADMIN 권한 체크
- 변경하려는 카테고리가 본인 회사에서 지정한 카테고리인지 확인
- 모든 조건 만족 시 카테고리 수정

Feat : 카테고리 수정 기능 구현 (#57)

---

src/main/java/com/project/comgle/controller/BookMarkController.java
src/main/java/com/project/comgle/entity/BookMarkFolder.java
src/main/java/com/project/comgle/service/BookMarkService.java

feat/52/modifyBookMarkFolder-> dev
- 즐겨찾기 폴더 수정 기능
- 즐겨찾기 폴더명 중복 추가 단계에서 예외처리
- 전체적인, 즐겨찾기 폴더가 존재하지 않을때의 예외처리
- BookMarkController에서 userDetails.getUser()를 userDetails.getMember() 로 변경

Feat : 즐겨찾기 폴더 수정 기능 (#52)(#51)

---

src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/dto/response/CategoryResponseDto.java
src/main/java/com/project/comgle/entity/Category.java
src/main/java/com/project/comgle/repository/CategoryRepository.java
src/main/java/com/project/comgle/security/UserDetailsImpl.java
src/main/java/com/project/comgle/security/UserDetailsServiceImpl.java
src/main/java/com/project/comgle/service/CategoryService.java

feat/60/find-categories -> develop
- Token을 통한 접속 계정 회사 식별
- 식별된 Company를 통한 해당 사내 카테고리 전체조회
- 기존 UserDetailsImpl에 Company 필드 추가

Feat : 카테고리 전체 조회 기능 (#60)

---

src/main/java/com/project/comgle/controller/BookMarkController.java
src/main/java/com/project/comgle/dto/response/BookMarkFolderResponseDto.java
src/main/java/com/project/comgle/repository/BookMarkFolderRepository.java
src/main/java/com/project/comgle/service/BookMarkService.java

feat/63/bookMarkRefactor-> dev
- 즐겨찾기 전체 기능 바뀐 Api와 요구사항 적용
Postman 테스트 결과 이상 없습니다. (확인함)

Refactor : 즐겨찾기 전체 기능에 바뀐 Api와 요구사항 적용 (#63)

---

src/main/java/com/project/comgle/controller/CommentController.java
src/main/java/com/project/comgle/dto/request/CommentRequestDto.java
src/main/java/com/project/comgle/entity/Category.java
src/main/java/com/project/comgle/entity/Comment.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/service/CommentService.java

feat/28/comment_post -> dev
- CommentController.java
- CommentRequestDto.java
- CommentService.java
- CommentRepository.java

feat : 댓글등록 구현 #28

---

src/main/java/com/project/comgle/controller/BookMarkController.java
src/main/java/com/project/comgle/repository/BookMarkRepository.java
src/main/java/com/project/comgle/service/BookMarkService.java

feat/53/myPost-> dev
- 마이페이지 즐겨찾기 폴더 별 조회 기능

Feat : 마이페이지 즐겨찾기 폴더 별 조회 기능 (#53)

---

src/main/java/com/project/comgle/controller/CommentController.java
src/main/java/com/project/comgle/dto/response/CommentResponseDto.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/service/CommentService.java

feat/78/commet_get -> dev
- 댓글 URL 수정
- CommentController.java
- CommentResponseDto.java
- CommentRepository.java
- CommentService.java

feat : 댓글조회 구현 (#78)

---

src/main/java/com/project/comgle/controller/SearchController.java
src/main/java/com/project/comgle/dto/response/PostResponseDto.java
src/main/java/com/project/comgle/entity/Keyword.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/repository/KeywordRepository.java
src/main/java/com/project/comgle/repository/PostRepository.java
src/main/java/com/project/comgle/service/PostService.java
src/main/java/com/project/comgle/service/SearchService.java

feat/82/search-keyword-> develop
- 키워드 검색 조회 기능 구현
- 게시글 작성 시 동일 키워드 입력하면 1번만 작성 되도 List -> set으로 변경

Feat : 메인페이지 키워드 검색 조회 #83

---

src/main/java/com/project/comgle/controller/CommentController.java
src/main/java/com/project/comgle/dto/request/CommentRequestDto.java
src/main/java/com/project/comgle/entity/Comment.java
src/main/java/com/project/comgle/service/BookMarkService.java
src/main/java/com/project/comgle/service/CommentService.java
src/main/java/com/project/comgle/service/MemberService.java

feat/86/comment_put -> dev
- CommentController.java
- CommentService.java

Feat : 댓글수정 구현

---

src/main/java/com/project/comgle/controller/SearchController.java
src/main/java/com/project/comgle/dto/response/PostResponseDto.java
src/main/java/com/project/comgle/dto/response/SearchResponseDto.java
src/main/java/com/project/comgle/entity/Keyword.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/repository/KeywordRepository.java
src/main/java/com/project/comgle/repository/PostRepository.java
src/main/java/com/project/comgle/service/PostService.java
src/main/java/com/project/comgle/service/SearchService.java

feat/82/search-keyword-> develop
- SearchResponseDto가 누락되어 있어 추가합니다.

Fix : 키워드 조회 수정

---

src/main/java/com/project/comgle/controller/PostController.java
src/main/java/com/project/comgle/controller/SearchController.java
src/main/java/com/project/comgle/repository/CategoryRepository.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/repository/PostRepository.java
src/main/java/com/project/comgle/service/SearchService.java

feat/82/search-category-> develop
- Searched Page 카테고리 검색 기능 추가
- PostController url API 명세서 변경대로 수정
- CommentRepository에서 merge 하며 잘못 반영된 부분 복귀

Feat : Searched Page 카테고리 검색 조회 기능  #82

---

src/main/java/com/project/comgle/controller/BookMarkController.java
src/main/java/com/project/comgle/controller/CategoryController.java
src/main/java/com/project/comgle/controller/MemberController.java
src/main/java/com/project/comgle/dto/common/ErrorResponse.java
src/main/java/com/project/comgle/dto/common/SuccessResponse.java
src/main/java/com/project/comgle/exception/CustomException.java
src/main/java/com/project/comgle/exception/ExceptionEnum.java
src/main/java/com/project/comgle/exception/GlobalExceptionHandler.java
src/main/java/com/project/comgle/jwt/JwtAuthFilter.java
src/main/java/com/project/comgle/service/BookMarkService.java

feat/92/exceptionDto-> dev
- 구조 잡기
- 즐겨찾기 예외처리 변경 완료

Refactor : 예외처리 (#92)

---

src/main/java/com/project/comgle/controller/CommentController.java
src/main/java/com/project/comgle/service/CommentService.java

refactor/94/comment_CustomException -> dev
- Exception -> CustionException으로 예외던지기(ExceptionEnum)
- success message 영문으로 변경
- CommentController swagger 오류수정

Refactor : CommentService CustomException 적용 (#94)

---

src/main/java/com/project/comgle/controller/MyPageController.java
src/main/java/com/project/comgle/dto/response/PostResponseDto.java
src/main/java/com/project/comgle/repository/PostRepository.java
src/main/java/com/project/comgle/service/MyPageService.java

feat/96/mypage_allget -> dev
- MyPageController.java
- MyPageService.java

Feat : 내 게시글 전체조회 구현 (#96)

---

src/main/java/com/project/comgle/controller/PostController.java
src/main/java/com/project/comgle/entity/Log.java
src/main/java/com/project/comgle/repository/LogRepository.java
src/main/java/com/project/comgle/service/PostService.java

feat/101/log_1 -> dev
- Post update 시, 로그생성
- 말랑이님이 해당 페이지를 편집했습니다.
- 편집한 시간 : 2023-03-20

Feat : 로그1차구현(차선책) (#101)

---

src/main/java/com/project/comgle/config/WebSecurityConfig.java
src/main/java/com/project/comgle/controller/PostController.java
src/main/java/com/project/comgle/dto/common/SchemaDescriptionUtils.java
src/main/java/com/project/comgle/dto/response/PostResponseDto.java
src/main/java/com/project/comgle/dto/response/SearchResponseDto.java
src/main/java/com/project/comgle/repository/BookMarkRepository.java
src/main/java/com/project/comgle/repository/CommentRepository.java
src/main/java/com/project/comgle/repository/LogRepository.java
src/main/java/com/project/comgle/service/PostService.java

feat/117/read-post-> develop
- 다른 분들이 서버 올리시면 이 부분도 꼭 pull 받아서 배포 부탁드립니다.
- ResponseDto에 조회수, 편집상태 추가
- sse cors 이슈 해결
- Api와 다른 url 수정
- postService 삭제 버그 수정
- swagger 추가 적용
- sse name, data 수정

Fix : 조회 Response, sse cors, post 삭제 기능 수정, post url 수정 #117

---

src/main/java/com/project/comgle/controller/PostController.java
src/main/java/com/project/comgle/service/PostService.java

feat/tmp-editingStatus-> develop
- 임시로 수정 상태 변경하는 API 하나 추가했습니다.

Feat : 임시 편집 상태 수정 기능

---

src/main/java/com/project/comgle/service/PostService.java

feat/119/CICD-> develop
- CI/CD 구현 테스트

Feat : CI / CD 구현 #119
